name = "MineOptimiz Fabric 1.21.8"
author = "Small__Mushroom"
version = "3.218.1-fabric+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff36b248847a2c79523360d6234ff0b4125712f3465055553c7a02578c2a444e"

[versions]
fabric = "0.18.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
