name = "MineOptimiz Fabric 1.21.4"
author = "Small__Mushroom"
version = "3.214.0-fabric+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "766b4abfdbd7bd9f6e6037ad61e9b605c66ffc2a4d7a02811526ecace441b0d6"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
