name = "MineOptimiz Fabric 1.21.4"
author = "Small__Mushroom"
version = "3.214.2-fabric+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3464a78293c9d898f9dad7c8a0c086413249f2efdd1c7c577ca34a11bcde53d2"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
