name = "MineOptimiz Cleanroom"
author = "Small__Mushroom"
version = "3.122.0-cleanroom+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fcdb01cb6aca2201030d8d03e3bcd38bee101374b754dae74db4c476c58225b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
