name = "MineOptimiz Cleanroom"
author = "Small__Mushroom"
version = "3.122.0-cleanroom+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b072701266d797ffab5506c2fb4fe58fb7921cc087fb0541dc2566f1b5ad0663"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
