name = "MineOptimiz Cleanroom"
author = "Small__Mushroom"
version = "3.122.0-cleanroom+commitid"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c8914cc91631f7e88c719320a36da64b5cff7b09c16f02504c9b6a22e99df92"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
