
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				arrow = true
				trader_llama = true
				cow = true
				tropical_fish = true
				chest_minecart = true
				pig = true
				slime = true
				skeleton = true
				bat = true
				rabbit = true
				zombie = true
				firework_rocket = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				wolf = true
				villager = true
				salmon = true
				wandering_trader = true
				zombie_villager = true
				boat = true
				item_frame = true
				hopper_minecart = true
				phantom = true
				minecart = true
				glow_squid = true
				cod = true
				witch = true
				squid = true
				wither = true
				spider = true
				creeper = true
				enderman = true

