name: Export Modrinth Pack

on:
  push:
    branches-ignore:
      - 'removing*'
    tags-ignore:
      - '*_latest*'
    paths-ignore: 
      - '*.md'
  workflow_dispatch:

jobs:
  Export-Modpack:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true 
          token: ${{ secrets.REFRESH_INDEX }} 
          fetch-depth: 0 
        
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh index
        run: |
          cd overrides
          packwiz refresh

      - name: Commit changes
        id: commit-check
        run: |
          git add overrides/pack.toml overrides/index.toml
            

          if [ -z "$(git status --porcelain overrides/pack.toml overrides/index.toml)" ]; then
            exit 0
          fi
            
          git commit -m "[skip ci] Refresh index"
          git push

      - name: Process Metadata
        run: |
          RELEASES_ID=1
          echo "VERSION=3.211.5" >> $GITHUB_ENV  
          echo "MC_VERSION=1.21.1" >> $GITHUB_ENV
          echo "LOADER=neoforge" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          sed -i "s/commitid/$SHORT_SHA/g" ./overrides/pack.toml
          sed -i "s/commitid/$SHORT_SHA/g" ./overrides/config/fancymenu/user_variables.db
      
      - name: Export Modrinth Pack
        run: |
          cd overrides
          packwiz modrinth export
          mv ./*.mrpack "MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.RELEASES_ID }}.mrpack"
      
      - name: Upload MineOptimiz to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.RELEASES_ID }}
          path: ./overrides/*.mrpack