name: Export Modrinth Pack

on:
  push:
    branches-ignore:
      - 'removing*'
    tags-ignore:
      - '*_latest*'
    paths-ignore: 
      - '*.md'
  workflow_dispatch:

jobs:
  Export-Modpack:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true 
          token: ${{ secrets.REFRESH_INDEX }} 
          fetch-depth: 0 
        
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false    

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh index
        run: |
          cd modpack_dir
          packwiz refresh

      - name: Commit changes
        id: commit-check
        run: |
          git add modpack_dir/pack.toml modpack_dir/index.toml
            

          if [ -z "$(git status --porcelain modpack_dir/pack.toml modpack_dir/index.toml)" ]; then
            echo "::notice::No changes detected"
            exit 0
          fi
            
          git commit -m "[skip ci] Refresh index"
          
          for i in {1..5}; do
          git push && break || sleep 15  # 增加重试次数和间隔
          done

      - name: Process Metadata
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "VERSION=3.122.0" >> $GITHUB_ENV  
          echo "MC_VERSION=1.12.2" >> $GITHUB_ENV
          echo "LOADER=forge" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          sed -i "s/commitid/$SHORT_SHA/g" ./modpack_dir/pack.toml
#          sed -i "s/commitid/$SHORT_SHA/g" ./modpack_dir/config/fancymenu/user_variables.db
#          sed -i "s/commitid/$SHORT_SHA/g" ./modpack_dir/config/modpack-update-checker/config.json
      
      - name: Export Modrinth Pack
        run: |
          cd modpack_dir
          packwiz curseforge export
          mv ./*.zip "MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.SHORT_SHA }}.zip"
      
      - name: Upload MineOptimiz to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.SHORT_SHA }}
          path: ./modpack_dir/*.zip
     
      - name: Upload MineOptimiz to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "MineOptimiz ${{ env.MC_VERSION }} ${{ env.LOADER }} Testing Latest"
          automatic_release_tag: "${{ env.MC_VERSION }}_${{ env.LOADER }}_latest_testing"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASES }}"
          files: ./modpack_dir/*.zip
          prerelease: true
        