name: Export Modrinth Pack

on:
  push:
    branches-ignore:
      - 'removing*'
    tags-ignore:
      - '*_latest*'
    paths-ignore: 
      - 'README.md'
  workflow_dispatch:

jobs:
  Export-Modpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true 
          token: ${{ secrets.REFRESH_INDEX }} 
          fetch-depth: 0 
        
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh index
        run: |
          cd overrides
          packwiz refresh

      - name: Commit changes
        id: commit-check
        run: |
          git add overrides/pack.toml overrides/index.toml
            

          if [ -z "$(git status --porcelain overrides/pack.toml overrides/index.toml)" ]; then
            echo "::notice::No changes detected"
            exit 0
          fi
            
          git commit -m "[skip ci] Refresh index"
          
          for i in {1..5}; do
          git push && break || sleep 15  # 增加重试次数和间隔
          done

      - name: Process Metadata
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "VERSION=3.201.5" >> $GITHUB_ENV  
          echo "MC_VERSION=1.20.1" >> $GITHUB_ENV
          echo "LOADER=forge" >> $GITHUB_ENV
          echo "RELEASES_ID=1" >> $GITHUB_ENV
          sed -i "s/commitid/${{ env.RELEASES_ID }}/g" ./overrides/pack.toml
          sed -i "s/commitid/${{ env.RELEASES_ID }}/g" ./overrides/config/modpack-update-checker/config.json
      
      - name: Export Modrinth Pack
        run: |
          cd overrides
          packwiz modrinth export
          mv ./*.mrpack "MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.RELEASES_ID }}.mrpack"
      
      - name: Upload MineOptimiz to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MineOptimiz v${{ env.VERSION }}-${{ env.LOADER }}+${{ env.RELEASES_ID }}
          path: ./overrides/*.mrpack