name: Refresh index

on:
  push: 
    branches: '21.1/fabric_testing'
  workflow_dispatch:  

jobs:
  refresh-index-and-commit:
    runs-on: ubuntu-latest 
    permissions:
      contents: write 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true 
          token: ${{ secrets.REFRESH_INDEX }} 
          fetch-depth: 0 

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: true

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest


      - name: Refresh index
        run: |
          cd overrides
          packwiz refresh

      - name: Commit changes
        id: commit-check
        run: |
          git add overrides/pack.toml overrides/index.toml
            

          if [ -z "$(git status --porcelain overrides/pack.toml overrides/index.toml)" ]; then
            echo "::notice::No changes detected"
            exit 0
          fi
            
          git commit -m "[skip ci] Refresh index"
          
          for i in 1 2 3; do
            git push && break || sleep 5
          done